apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-proxy
  labels:
    app: iso-share
    component: html-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iso-share
      component: html-proxy
  template:
    metadata:
      labels:
        app: iso-share
        component: html-proxy
    spec:
      containers:
        - name: nginx-iframe-proxy
          image: nibrev/nginx-iframe-proxy:latest
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: index-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: index-html
          configMap:
            name: html-proxy-index
      securityContext:
        seccompProfile:
          type: RuntimeDefault
